"""empty message

Revision ID: 229dc26c4a5b
Revises: 51f5ccfba190
Create Date: 2016-08-16 19:23:12.622760

"""

# revision identifiers, used by Alembic.
revision = '229dc26c4a5b'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_default_avatar', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_default_avatar')
    ### end Alembic commands ###
